"""alter telegram_id column

Revision ID: 4f647f1fbbdb
Revises: 
Create Date: 2024-10-18 17:30:24.052643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4f647f1fbbdb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mytest')
    op.drop_index('assignedToMac', table_name='serials')
    op.drop_index('serialNum', table_name='serials')
    op.drop_index('username', table_name='serials')
    op.drop_table('serials')
    op.alter_column('user', 'telegram_id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'telegram_id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               nullable=False)
    op.create_table('serials',
    sa.Column('serialNum', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('assignedToMac', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('lifetime', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('assignDuration', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_of_assignment', sa.DATE(), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('username', 'serials', ['username'], unique=True)
    op.create_index('serialNum', 'serials', ['serialNum'], unique=True)
    op.create_index('assignedToMac', 'serials', ['assignedToMac'], unique=True)
    op.create_table('mytest',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
